apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ingest-encode-data
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}
      dag:
        tasks:
          # Pull and process the metadata currently stored in ENCODE.
          - name: process-metadata
            templateRef:
              name: process-encode-data
              template: main
            arguments:
              parameters:
                - name: gcs-prefix
                  value: '{{ $gcsPrefix }}'

          # Ingest the processed tabular data.
          - name: ingest-metadata
            templateRef:
              name: ingest-processed-data
              template: main
            arguments:
              parameters:
                - name: gcs-prefix
                  value: '{{ $gcsPrefix }}'
