cron:
  enable: true
  # Every Sunday at 3:30am
  schedule: '30 3 * * Sun'
  timezone: 'America/New_York'
dataflow:
  region: us-west1
  workerMachineType: n1-standard-1
  autoscaling:
    minWorkers: 4
    maxWorkers: 8
  useFlexRS: false
