cron:
  enable: true
  # Every Sunday at 3:30am
  schedule: '30 3 * * Sun'
  timezone: 'America/New_York'
dataflow:
  region: us-west1
  workerMachineType: n1-standard-1
  autoscaling:
    minWorkers: 4
    maxWorkers: 8
  useFlexRS: false
volumes:
  storageClass: standard
argoTemplates:
  generatePVC:
    create: true
    name: create-pvc
  deletePVC:
    create: true
    name: delete-pvc
  downloadS3File:
    create: true
    name: download-s3-file
  copyToGCS:
    create: true
    name: gsutil-upload
smokeTest:
  enable: false
bigquery:
  jadeData:
    dataset: datarepo_broad_dsp_encode
